//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullElectricCars.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class carDetails
    {
        public int cid { get; set; }
        public int mid { get; set; }
        public string model { get; set; }

        [DataType(DataType.Currency)]
        public double price { get; set; }

        public double mpc { get; set; }


        public string image { get; set; }
        public string video { get; set; }
        public Nullable<int> likes { get; set; }
    
        public virtual manufacturers manufacturers { get; set; }

        //it will be used to upload image
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
