//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullElectricCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manufacturers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public manufacturers()
        {
            this.carDetails = new HashSet<carDetails>();
        }
    
        public int mid { get; set; }
        public string manufacturerName { get; set; }
        public string addressLine1 { get; set; }
        public string city { get; set; }
        public string postcode { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string site { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carDetails> carDetails { get; set; }
    }
}
